name: v_player
description: 基于苹果CMS8.0的资源站收集视频APP

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.4+19

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  path: ^1.8.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  provider: ^6.0.4
  synchronized: ^3.0.0+3
  dio: ^4.0.4
  easy_refresh: ^3.0.4+2
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.2
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  permission_handler: ^10.1.0
  bot_toast: ^4.0.3
  flutter_html: ^3.0.0-alpha.6
#  connectivity_plus: ^2.3.9
  connectivity_plus: ^6.0.3

  video_player: ^2.4.7
  chewie: ^1.3.5
  auto_orientation: ^2.2.1
  flutter_screen_wake: ^1.0.2
  volume_controller: ^2.0.4
  flutter_bugly: ^0.4.4

#  m3u8_downloader:
#    git:
#      url: https://github.com/DK3369/m3u8_downloader.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/data/

